# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=50, verbose_name='Type')),
                ('architecture', models.CharField(choices=[('32', '32 Bits'), ('64', '64 Bits')], default='64', max_length=50, verbose_name='Architecture')),
                ('image_name', models.CharField(max_length=150, null=True, verbose_name='Image Name')),
                ('image_url', models.CharField(max_length=200, null=True, verbose_name='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('recipe_type', models.CharField(choices=[('ansible', 'Ansible'), ('chef', 'Chef')], default='ansible', max_length=50, verbose_name='Type')),
                ('recipe_code', models.TextField(null=True, verbose_name='Recipe Code')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=50, verbose_name='OS Type')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('external_id', models.CharField(max_length=200, null=True, unique=True, verbose_name='External ID')),
                ('server_type', models.CharField(choices=[('docker', 'Docker'), ('vagrant', 'Vagrant')], default='docker', max_length=50, verbose_name='Server Type')),
                ('memory_size', models.IntegerField(null=True, verbose_name='Memory Size')),
                ('disk_size', models.IntegerField(null=True, verbose_name='Disk Size')),
                ('internal_ip', models.CharField(max_length=50, null=True, verbose_name='Internal IP')),
                ('external_ip', models.CharField(max_length=50, null=True, verbose_name='External IP')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('creation', 'Creation'), ('done', 'Done'), ('error', 'Error')], default='draft', max_length=50, verbose_name='State')),
                ('base_url', models.CharField(max_length=255, null=True, verbose_name='Base URL')),
                ('initial_command', models.CharField(max_length=200, null=True, verbose_name='Initial Command')),
                ('initial_port', models.IntegerField(null=True, verbose_name='Initial Port')),
                ('final_port', models.IntegerField(null=True, verbose_name='Final Port')),
                ('operational_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.OperationalSystem')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.Server')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Recipe')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set([('name', 'recipe_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='operationalsystem',
            unique_together=set([('name', 'os_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('server_type', 'name')]),
        ),
    ]
