# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalsystem',
            options={'verbose_name': 'Operational System', 'verbose_name_plural': 'Operational Systems'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server/Container', 'verbose_name_plural': 'Servers/Containers'},
        ),
        migrations.AddField(
            model_name='server',
            name='message_error',
            field=models.TextField(blank=True, null=True, verbose_name='Message Erros'),
        ),
        migrations.AlterField(
            model_name='operationalsystem',
            name='image_name',
            field=models.CharField(blank=True, help_text='Image Name is used on Docker Containers creation!', max_length=150, null=True, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='operationalsystem',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_code',
            field=models.TextField(blank=True, null=True, verbose_name='Recipe Code'),
        ),
        migrations.AlterField(
            model_name='server',
            name='base_url',
            field=models.CharField(blank=True, default='unix://var/run/docker.sock', help_text='This URL is used on Docker containers to point a Kernel Server.', max_length=255, null=True, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disk Size'),
        ),
        migrations.AlterField(
            model_name='server',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='external_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='External IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='final_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='initial_command',
            field=models.CharField(blank=True, default='/bin/sh', max_length=200, null=True, verbose_name='Initial Command'),
        ),
        migrations.AlterField(
            model_name='server',
            name='initial_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initial Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='internal_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='memory_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memory Size'),
        ),
        migrations.AlterField(
            model_name='server',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Recipe'),
        ),
        migrations.AlterField(
            model_name='server',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('creation', 'Creation'), ('done', 'Done'), ('detroyed', 'Destroyed'), ('error', 'Error')], default='draft', max_length=50, verbose_name='State'),
        ),
    ]
